version: '3.7'

services:
  web:
    build: .
    volumes: &web-volumes
      - &app-volume .:/aviasales_api:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - ruby-2.7.4-gems:/usr/local/bundle
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      - db
    environment: &web-environment
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    command: bundle exec rails s -b '0.0.0.0' -p 3000

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  ruby-2.7.4-gems: